version: "3.8" 

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cloud_notes_app
      - JWT_SECRET=${JWT_SECRET:-supersecret_jwt_key_that_should_be_long}
    depends_on:
      - mongodb

  client:
    build: ./client
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  mongo-data: